fix(cve): update packages
StatCan/kubeflow-pipelines pull request #18
Opened 2022-01-27 15:38 UTC by Jose-Matsuda

hacky but seems to work. this is the same cve that is on the `branch-1.5.1`

2022-01-27 21:26 UTC, Jose-Matsuda commented
possible funny business, so like in our `branch-1.5.1` I was testing using a kind cluster, as well as using the 
```
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.2.0"
kubectl wait --for condition=established --timeout=60s crd/applications.app.k8s.io
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=1.2.0"
```

and then in `frontend` running `NAMESPACE=kubeflow npm run start:proxy` I observed the following
![image](https://user-images.githubusercontent.com/23174198/151444764-d9932c6e-0594-4412-a5df-9114f0a1c583.png)

Where `asdaa` was on `stc-master` and `asd` was running on the `json-schema-cve` branch

2022-01-27 21:27 UTC, Jose-Matsuda commented
Upon checking logs I can see
![image](https://user-images.githubusercontent.com/23174198/151446423-11e85521-87a3-435e-a29d-40e0ec1c424b.png)

2022-01-28 15:17 UTC, Jose-Matsuda commented
Am currently checking if the pipelines fail. I am using the `Tutorail DSL -Control Structures` pipeline, and a default experiment

On branch 1.5.1 the result is
![image](https://user-images.githubusercontent.com/23174198/151572514-d5fe4ca4-b5b7-4ce7-b81f-34c98b5f6f50.png)

on branch 1.5.1 with the cve fix the result is the same.

2022-01-28 15:30 UTC, wg102 requested changes

2022-01-28 15:30 UTC, wg102 commented on frontend/Dockerfile
> +
remove new line

2022-01-28 15:30 UTC, wg102 commented on frontend/Dockerfile
> +## FORCE SOME THINGS
Please write a significant message, possibly mentionning the cve or at least the ticket linked to it.

2022-01-28 15:43 UTC, Jose-Matsuda commented
on 1.2.1 the experiments are different so can't be super sure. 
![image](https://user-images.githubusercontent.com/23174198/151576106-6aaae850-8736-4b61-a9df-5db68315d442.png)
![image](https://user-images.githubusercontent.com/23174198/151576949-1003fbb8-dc8f-4b6b-94b2-2a8ebd055fb5.png)

2022-01-28 15:44 UTC, Jose-Matsuda commented
Again i'm no pipelines expert so it may be best to have more experienced people test this. If it completely breaks the rollback should not be difficult

2022-01-28 18:25 UTC, wg102 approved these changes

2022-01-28 18:25 UTC, merged